## Python Programming Lab [CCP202]
## Practical no. 6

## Name: Samruddhi Rathi

## Roll no: C1-14

1. Write a python code for addition, subtraction and multiplication of two 4x4 matrices. [Use
numpy]

In [2]:
import numpy as np
x = np.array([[1,2,3,3],[3,4,5,6],[1,2,3,4],[1,7,8,9]])
y = np.array([[1,1,1,1],[2,2,2,7],[9,8,9,7],[4,5,6,1]])
print("X=",x)
print("Y=",y)

X= [[1 2 3 3]
 [3 4 5 6]
 [1 2 3 4]
 [1 7 8 9]]
Y= [[1 1 1 1]
 [2 2 2 7]
 [9 8 9 7]
 [4 5 6 1]]


In [24]:
print("Addition is \n",x+y)
print("Subtraction is \n ",x-y)
print("Multiplication is\n",x.dot(y))
print("Division is\n",x/y)

Addition is 
 [[ 2  3  4  4]
 [ 5  6  7 13]
 [10 10 12 11]
 [ 5 12 14 10]]
Subtraction is 
  [[ 0  1  2  2]
 [ 1  2  3 -1]
 [-8 -6 -6 -3]
 [-3  2  2  8]]
Multiplication is
 [[ 44  44  50  39]
 [ 80  81  92  72]
 [ 48  49  56  40]
 [123 124 141 115]]
Division is
 [[1.         2.         3.         3.        ]
 [1.5        2.         2.5        0.85714286]
 [0.11111111 0.25       0.33333333 0.57142857]
 [0.25       1.4        1.33333333 9.        ]]


2. Write a NumPy program to compute the following for the given array.
Mean, median, mode, variance, and standard deviation.

In [8]:
import statistics as st
arr=np.array([1,2,3,4,5,6,7,8,9,10])
a=np.mean(arr)
b=np.var(arr)
c=np.std(arr)
d=np.median(arr)
print("\nMean=",a)
print("\nVariance=",b)
print("\nStandard Deviation=",c)
print("\nMedian=",d)
print("\nMode=",st.mode(arr))


Mean= 5.5

Variance= 8.25

Standard Deviation= 2.8722813232690143

Median= 5.5

Mode= 1


3. Randomly generate the marks of the 80 students in the range of 40 to 95. Write a NumPy
program to compute the 70 percentiles for all elements in a given array. (Hint: use
np.random.randint (start, stop, no_of_items) for list generation) (Hint: Use np.percentile)

In [9]:
array=np.random.randint(40,95,80)
print(array)
print("70th percentile of array: ",np.percentile(array,70))

[45 58 66 55 47 61 82 46 56 94 66 50 80 40 44 83 55 42 66 87 41 50 70 65
 90 66 90 67 81 84 53 51 60 81 78 54 70 57 67 85 48 71 66 62 90 63 80 44
 75 78 43 78 44 67 52 45 65 89 53 47 53 74 49 62 76 93 54 91 86 47 63 90
 74 45 67 60 64 69 49 68]
70th percentile of array:  74.0


4. You are given a space separated list of nine integers. Your task is to convert this list into
a 3x3 NumPy array.Eg: input: 1 2 3 4 5 6 7 8 9
Output:
[ [1 2 3]
[4 5 6]
[7 8 9] ]
Further, compute the determinant and inverse of the array manually as well as programmatically
using python.
[HINT: to find determinant use linear algebra package under numpy. Add these statements i.e.
import numpy as np
from numpy import linalg
np.linalg.det(a)]

In [10]:
import numpy as np
from numpy import linalg
arr1=np.arange(1,10)
arr2=arr1.reshape(3,3)
print("Input: ",arr1)
print("Outout:\n",arr2)

Input:  [1 2 3 4 5 6 7 8 9]
Outout:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
det = np.linalg.det(arr2)
print("Determinant= ",int(det))

Determinant=  0


In [14]:
i = np.linalg.inv(arr2)
print("Inverse =\n",i)

Inverse =
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


5. Create a 5 by 2 integer array from a range between 100 to 200 such that the difference
between each element is 10. Print the same.

In [15]:
array=np.arange(100,200,10)
arr=array.reshape(5,2)
print(arr)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


6) Write a program to print the checkerboard pattern of n x n using NumPy.
The problem statement is given n, print the checkerboard pattern for a n x n matrix considering
that 0 for black and 1 for white.

In [16]:
import numpy as np
 
# function to print Checkerboard pattern
def printcheckboard(n):
     
    print("Checkerboard pattern for n=10:")
 
    # create a n * n matrix
    x = np.zeros((n, n), dtype = int)
 
    # fill with 1 the alternate rows and columns
    x[1::2, ::2] = 1
    x[::2, 1::2] = 1
     
    # print the pattern
    for i in range(n):
        for j in range(n):
            print(x[i][j], end =" ")
        print()
 
 
# driver code
n = 10
printcheckboard(n)

Checkerboard pattern for n=10:
0 1 0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 1 0 
0 1 0 1 0 1 0 1 0 1 
1 0 1 0 1 0 1 0 1 0 


7) Write a program to sort a given array. sort an entire array, sort array in row wise, sort array in
column wise.
Note: Use sort method

In [17]:
arr=np.array([[10,2,36],[4,50,16],[745,68,91]])
print(arr)  

[[ 10   2  36]
 [  4  50  16]
 [745  68  91]]


In [18]:
# sorting an entire array
arr1=np.sort(arr)
print(arr1)

[[  2  10  36]
 [  4  16  50]
 [ 68  91 745]]


In [19]:
# sorting array column-wise
arr2=np.sort(arr,axis=0)
print("After column sorting:\n",arr2)

After column sorting:
 [[  4   2  16]
 [ 10  50  36]
 [745  68  91]]


In [20]:
# sorting array row-wise
arr3=np.sort(arr,axis=1)
print("After row sorting:\n",arr3)

After row sorting:
 [[  2  10  36]
 [  4  16  50]
 [ 68  91 745]]
